title: Konvert
description: Usage documentation of Konvert
theme: just-the-docs
baseurl: "/konvert"

url: https://mcarleio.github.io

aux_links:
  Konvert Repository: https://github.com/mcarleio/konvert

color_scheme: wider

plugins:
  - jekyll-target-blank

exclude:
  - src/
  - build.gradle.kts
  - build/
  - typeconverter/gen
